output "cluster_endpoint" {
  value        = "module.eks.cluster_endpoint"
  description  = "EKS control plane endpoint"
}

output "cluster_securoty_group_id" {
  value       = module.eks.cluster_security_group_id
  description = "Cluster control plane security group ids"
}

output "kubectl_config" {
  value       = module.eks.kubeconfig 
  description = "kubectl config as generated by eks module"
}

output "config_map_aws_auth" {
  value        = module.eks.config_map_aws_auth
  description  = "A k8s config to authenticate to this EKS cluster"
}

output "region" {
  value = var.region
  description = "AWS region"
}

output "cluster_name" {
  value = local.cluster_name
}